-- Manual seed script for App_Utilisateurs
-- Run this if automatic seeding didn't work

-- First, make sure table exists
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[App_Utilisateurs]') AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[App_Utilisateurs] (
        [Id] INT PRIMARY KEY,
        [Username] NVARCHAR(100) NOT NULL,
        [PasswordHash] NVARCHAR(200) NOT NULL,
        [Role] NVARCHAR(50) NOT NULL,
        [FullName] NVARCHAR(200) NOT NULL,
        [Email] NVARCHAR(200) NOT NULL
    );
    PRINT 'App_Utilisateurs table created';
END
GO

-- Clear existing data
DELETE FROM App_Utilisateurs;
GO

-- Insert seed users
-- Password for ALL users: KTBio@2026
-- These are BCrypt hashes generated by the PasswordHelper

INSERT INTO App_Utilisateurs (Id, Username, PasswordHash, Role, FullName, Email) VALUES
(1, 'admin', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'Admin', 'Administrateur KTBio', 'admin@ktbio.tn'),
(2, 'anis.bk', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'Admin', 'Anis Ben Khadija', 'anis@ktbio.tn'),
(3, 'yamen.h', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'User', 'Yamen Hadhri', 'yamen@ktbio.tn'),
(4, 'mourad.bk', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'User', 'Mourad Ben Khadija', 'mourad@ktbio.tn'),
(5, 'iheb.b', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'User', 'Iheb Belarbi', 'iheb@ktbio.tn'),
(6, 'imen.l', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'User', 'Imen Lahouioui', 'imen@ktbio.tn'),
(7, 'marwa.t', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'Vendeur', 'Marwa Troudi', 'marwa@ktbio.tn'),
(8, 'ines.bk', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'User', 'Ines Ben Khadija', 'ines@ktbio.tn'),
(9, 'lilia.c', '$2a$12$LQ7Z8VqF5X9mKxF9YZ9Z9.9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9e', 'User', 'Lilia Charmiti', 'lilia@ktbio.tn');
GO

-- Verify insertion
SELECT Id, Username, Role, FullName, Email FROM App_Utilisateurs ORDER BY Id;
GO

PRINT 'Seed data inserted successfully!';
PRINT 'Default password for ALL users: KTBio@2026';
GO
